Merge bug fix
Fixed a few merge bugs that cropped up.
One still exists that causes an error on play.
Be advised, Liam's branch was branched and asked to be checked, I merged mine before this check, either branch could have caused it or the error may have already existed? Please see the error below, pertains to the state machine and its transitions.

NullReferenceException: Object reference not set to an instance of an object
State.CheckTransitions (.StateController controller) (at Assets/AI/BaseAIScripts/States/State.cs:31)
State.UpdateState (.StateController controller) (at Assets/AI/BaseAIScripts/States/State.cs:16)
StateController.Update () (at Assets/AI/BaseAIScripts/StateController.cs:91)